#!/bin/bash

iptablesWithSudo(){
    sudo iptables "$@"
}
usage() {
    echo "Usage: $0 [start|reset|status|flush]"
    exit 1
}
commands="commands"

start_firewall() {
    echo "Starting firewall..."
    #Chck if commands empty
    if [ ! -s "$commands" ]; then
        echo "The file '$commands' is empty. Please Fill it with commands."
        echo "If you have no commands , feal free to explore the pre made profiles  in profiles ."
        echo "Copy any profile contents and past it in  '$commands' the re run the script."
    fi


    
}
reset_firewall() {
    echo "Stopping firewall..."
    $iptablesWithSudo -F
    $iptablesWithSudo -P INPUT ACCEPT
    $iptablesWithSudo -P FORWARD ACCEPT
    $iptablesWithSudo -P OUTPUT ACCEPT
    echo "Firewall stopped. All traffic is allowed."
}
status_firewall() {
    echo "Current $iptablesWithSudo rules:"
    iptablesWithSudo -L -n -v
}

flush_firewall() {
    echo "Flushing all $iptablesWithSudo rules..."
    sudo $iptablesWithSudo -F
    echo "All rules flushed."
}

if [ $# -ne 1 ]; then
    usage
fi

case $1 in
    start)
        start_firewall
        ;;
    reset)
        reset_firewall
        ;;
    status)
        status_firewall
        ;;
    flush)
        flush_firewall
        ;;
    *)
        usage
        ;;
esac

