#!/bin/bash
#================== Vars =================>
filename="commands"
iptables_rules_backup_dir="backup" 
conf_file=".env"

# colors
GREEN="\e[32m"
YELLOW="\e[33m"
RED="\e[31m"
RESET="\e[0m"
#================== End Vars =============>
#================== Functions ============>
print_help (){
echo "This Bash script simplifies the management of iptables on Linux systems by providing an easy-to-use interface for listing, creating, flushing, and deleting firewall rules. It allows users to quickly review existing rules, add new ones , and reset their firewall configuration as needed."

}
print_banner (){

cat <<EOF
###################################
# ____              ____  _     _ #
#|  _ \ ___ _ __   / ___|| |__ (_)#
#| |_) / _ \ '_ \  \___ \| '_ \| |#
#|  __/  __/ | | |  ___) | | | | |#
#|_|   \___|_| |_| |____/|_| |_|_|#
   iptables Rules Automation Tool 
###################################
EOF

}

#print success messages

print_s() {
    echo -e "${GREEN}$1${RESET}"
    return 0
}

#print warning messages
print_w() {
    echo -e "${YELLOW}$1${RESET}"
    return 1
}

#print error messages 
print_e() {
    echo -e "${RED}$1${RESET}"
    exit 2
}

iptablesWithSudo(){
    sudo iptables "$@"
}

#This iscript is tested on Debian-based distribution , if not Debian-based distribution ask the use if want to continue
check_not_debian_distribution() {
    if ! grep -q -E 'Debian|Ubuntu|Linux Mint|Raspbian' /etc/*release; then
        print_w "This script has been tested on Debian-based distributions only , it seem that you are using other distro ."
        read -p "Do you want to continue? (y/n): " choice
        if [[ ! "$choice" == [Yy] ]]; then
            print_e "Exiting..."
        fi
    fi
}

env() { #usage env "das"

    local key="$1"
    local file=".env"

    if [[ ! -f "$file" ]]; then
        print_e "Configuration file not found!"
    fi
    local value=$(grep -E "^$key=" "$file" | cut -d'=' -f2-)

    if [[ -n "$value" ]]; then
        return "$value"
    else
        print_e "Key '$key' not found in the configuration file."
    fi
}

usage() {
    print_w "Usage: $0 [Commands] <Options> "
    echo "Commands :

    -R -rules		rules managent
    -H -help		print the script description
    "
    echo "Options :

    --a         add rules (all rules must be in commands file)
    --l		list all rules
    --f		delete all rules 
    --d 	delete one rule by chain (FORWARD , INPUT ,OUTPUT) and id (get it from $0  -rules --l)
    exemple :
    $0 -rules --d FORWARD 1 
    "
    exit 1
}

# Rules Functions
check_iptables_rules() {

    if [ "$( sudo iptables-save | grep '^\-' | wc -l )" -eq 0 ]; then
        print_e "No iptables rules found. Stopping execution ."
    fi

}

backup_iptables_rules() {
    local backup_dir="$1"
    
    if [[ ! -d "$backup_dir" ]]; then
        mkdir -p "$backup_dir"
        if [[ $? -ne 0 ]]; then
            exit 1
        fi
    fi

    check_iptables_rules
    local backup_file="$backup_dir/iptables_deleted_rules_$(date +%Y-%m-%d_%H:%M:%S).txt"
    sudo iptables-save > "$backup_file"

    if [[ $? -eq 0 ]]; then
        print_s "Iptables rules backed up to $backup_file"
    else
        print_e "Something went wrong when trying to backup rules"
    fi
}

restore_iptables_rules() {
    local backup_dir="$1"

    if [[ ! -d "$backup_dir" ]]; then
        print_e "Directory $backup_dir does not exist. Exiting."

    fi

    echo "Available backup files in $backup_dir : "
    select backup_file in "$backup_dir"/*; do
        if [[ -f "$backup_file" ]]; then
            print_s  "You have selected: $backup_file"
            sudo iptables-restore < "$backup_file"
            if [[ $? -eq 0 ]]; then
                print_s "Iptables rules restored from $backup_file"
            else
                print_e "Failed to restore iptables rules."
            fi
            break
        else
            print_e "Invalid selection. Please choose a valid file."
        fi
    done
}

rules() {
  
    if [[ "$1" == "--a" ]]; then

    if [[ ! -f $filename ]]; then
        print_e "File not found!"
    fi

    while IFS= read -r line; do
        print_s "Executing: $line"
        sudo $line
    done < "$filename"

    elif [[ "$1" == "--l" ]]; then
        print_s "Listing rules ... "
        sleep 2
        iptablesWithSudo -L --line-numbers

    elif [[ "$1" == "--f" ]]; then
        check_iptables_rules 
        env "Rules_backup_on_deletion"
        if [ "$?" -eq 1 ]; then #check if backup rules activated
        backup_iptables_rules "$iptables_rules_backup_dir"
        fi
        iptablesWithSudo --flush
        print_s "All iptables rules flushed"
    elif [[ "$1" == "--d" ]]; then
         # Check if the rule ID is a valid number
        if ! [[ "$3" =~ ^[0-9]+$ ]]; then
            print_e "Invalid rule ID: $3 . It must be a number ."
        fi
        # Check correct chain , chose INPUT , FORWARD or OUTPUT
        chain=$2
        if [ "$chain" == "o" ]; then
            chain="OUTPUT"
        elif [[ "$chain" == "f" ]]; then
            chain="FORWARD"
        elif [[ "$chain" == "i" ]]; then
            chain="INPUT"
        else
            print_e "$chain is incorrect chain , chose i (for INPUT) , f (for FORWARD) or o (for OUTPUT) ."
        fi
        env "Rules_backup_on_deletion"
        if [ "$?" -eq 1 ]; then #check if backup rules activated
        backup_iptables_rules "$iptables_rules_backup_dir"
        fi
        iptablesWithSudo -D $chain $3
        print_s "iptables rule deleted ."


    elif [[ "$1" == "--r" ]]; then
        restore_iptables_rules "$iptables_rules_backup_dir"

    elif [[ "$1" == "--b" ]]; then
        backup_iptables_rules "$iptables_rules_backup_dir"

    else
        print_w "the '-rules' has no option like : $1 "
    fi
}

# End Rules Functions

#================== End Functions =================>
print_banner
check_not_debian_distribution

if [ $# -lt 1 ]; then
    usage
fi

case $1 in
    -rules | -R )
        rules $2 $3 $4
        ;;
    -help | -H )
        print_help
        ;;
    *)
        usage
        ;;
esac
