#!/bin/bash

#================== Vars =================>

filename="commands"
iptables_rules_backup_dir="backup" 
conf_file=".env"

#================== End Vars =============>

#================== Functions ============>

iptablesWithSudo(){
    sudo iptables "$@"
}

env() { #usage env "das"

    local key="$1"
    local file=".env"

    if [[ ! -f "$file" ]]; then
        echo "Configuration file not found!"
        return 1
    fi
    local value=$(grep -E "^$key=" "$file" | cut -d'=' -f2-)

    if [[ -n "$value" ]]; then
        echo "$value"
    else
        echo "Key '$key' not found in the configuration file."
        exit 1
    fi
}

usage() {
    echo "Usage: $0 [Commands] <Options> "
    #"[start|reset|status|flush]"
    echo "Commands :
    -rules		rules managent
    "
    echo "Options :
    --a     add rules (all rules must be in commands file)
    --l		list all rules
    --f		delete all rules 
    --d 	delete one rule by chain (FORWARD , INPUT ,OUTPUT) and id (get it from $0  -rules --l)
    exemple :
    $0 -rules --d FORWARD 1 
    "
    exit 1
}

# Rules Functions

check_iptables_rules() {

    if [ "$( sudo iptables-save | grep '^\-' | wc -l )" -eq 0 ]; then
        echo "No iptables rules found. Stopping execution."
        exit 1
    fi

}

backup_iptables_rules() {
    local backup_dir="$1"
    
    if [[ ! -d "$backup_dir" ]]; then
        mkdir -p "$backup_dir"
        if [[ $? -ne 0 ]]; then
            exit 1
        fi
    fi

    local backup_file="$backup_dir/iptables_rules_backup_$(date +%Y-%m-%d_%H:%M:%S).txt"
    sudo iptables-save > "$backup_file"

    if [[ $? -eq 0 ]]; then
        echo "Iptables rules backed up to $backup_file"
    else
        exit 1
    fi
}

restore_iptables_rules() {
    local backup_dir="$1"

    if [[ ! -d "$backup_dir" ]]; then
        echo "Directory $backup_dir does not exist. Exiting."
        exit 1
    fi

    echo "Available backup files in $backup_dir:"
    select backup_file in "$backup_dir"/*; do
        if [[ -f "$backup_file" ]]; then
            echo "You have selected: $backup_file"
            sudo iptables-restore < "$backup_file"
            if [[ $? -eq 0 ]]; then
                echo "Iptables rules restored from $backup_file"
            else
                echo "Failed to restore iptables rules."
            fi
            break
        else
            echo "Invalid selection. Please choose a valid file."
        fi
    done
}

rules() {
  
    if [[ "$1" == "--a" ]]; then

    if [[ ! -f $filename ]]; then
        echo "File not found!"
        exit 1
    fi

    while IFS= read -r line; do
        echo "Executing: $line"
        sudo $line
    done < "$filename"

    elif [[ "$1" == "--l" ]]; then
        echo "Listing rules"
        sleep 2
        iptablesWithSudo -L --line-numbers

    elif [[ "$1" == "--f" ]]; then
        check_iptables_rules 
        backup_iptables_rules "$iptables_rules_backup_dir" #backup rules in case of error by user
        iptablesWithSudo --flush
        echo "All iptables rules flushed"


    elif [[ "$1" == "--d" ]]; then
         # Check if the rule ID is a valid number
        if ! [[ "$3" =~ ^[0-9]+$ ]]; then
            echo "Invalid rule ID: $3 . It must be a number."
            exit 1
        fi

        # Check correct chain , chose INPUT , FORWARD or OUTPUT
        if [[ "$2" == "OUTPUT" || "$2" == "FORWARD"|| "$2" == "INPUT"  ]]; then
       
        #execute
        iptablesWithSudo -D $2 $3

        else
            echo "$2 is incorrect chain , chose INPUT , FORWARD or OUTPUT ."
        fi


    elif [[ "$1" == "--r" ]]; then
        restore_iptables_rules "$iptables_rules_backup_dir"

    elif [[ "$1" == "--b" ]]; then
        backup_iptables_rules "$iptables_rules_backup_dir"

    else
        echo "the '-rules' has no option like : $1 "
    fi
}

# End Rules Functions

#================== End Functions =================>

if [ $# -lt 2 ]; then
    usage
fi

case $1 in
    -rules)
        rules $2 $3 $4
        ;;
    *)
        usage
        ;;
esac
